sonar.projectKey=project-01-qlib
sonar.projectName=Project 01 - qlib
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=**/docs/**,**/examples/**,**/*.ipynb,**/node_modules/**

sonar.python.version=3.8,3.9,3.10,3.11
